apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=   # base64 encoded "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM=   # base64 encoded "postgres"
  POSTGRES_DB: cGxhbnRa   # base64 encoded "plantZ"
  DATABASE_URL: cG9zdGdyZXFsbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wbGFudFo=
